# Site settings
title: Some development notes ...
email: blog@jeremypaul.fr
description: "Sometimes I find things which I think are valuables. Here they are."
baseurl: ""
url: "http://pjerem.github.io"
twitter_username: jeremypaul_fr
github_username:  pjerem

# Build settings
markdown: kramdown
permalink: pretty
